### ISSUE TITLE
help

### ISSUE THREAD

**Issue by omegabr22** [cookiedragon234/JvmClassDumper#1]
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\ClassDump.java:3: error: package sun.jvm.hotspot.debugger does not exist
import sun.jvm.hotspot.debugger.AddressException;
                               ^
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\ClassDump.java:4: error: package sun.jvm.hotspot.debugger does not exist
import sun.jvm.hotspot.debugger.JVMDebugger;
                               ^
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\ClassDump.java:5: error: package sun.jvm.hotspot.memory does not exist
import sun.jvm.hotspot.memory.SystemDictionary;
                             ^
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\ClassDump.java:6: error: package sun.jvm.hotspot.oops does not exist
import sun.jvm.hotspot.oops.InstanceKlass;
                           ^
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\ClassDump.java:7: error: package sun.jvm.hotspot.runtime does not exist
import sun.jvm.hotspot.runtime.VM;
                              ^
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\ClassDump.java:8: error: package sun.jvm.hotspot.tools does not exist
import sun.jvm.hotspot.tools.Tool;
                            ^
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\ClassDump.java:9: error: package sun.jvm.hotspot.tools.jcore does not exist
import sun.jvm.hotspot.tools.jcore.ClassFilter;
                                  ^
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\ClassDump.java:10: error: package sun.jvm.hotspot.tools.jcore does not exist
import sun.jvm.hotspot.tools.jcore.ClassWriter;
                                  ^
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\ClassDump.java:22: error: cannot find symbol
public class ClassDump extends Tool {
                               ^
  symbol: class Tool
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\ClassDump.java:23: error: cannot find symbol
        private ClassFilter classFilter;
                ^
  symbol:   class ClassFilter
  location: class ClassDump
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\ClassDump.java:31: error: cannot find symbol
        public ClassDump(JVMDebugger d, String pkgList) {
                         ^
  symbol:   class JVMDebugger
  location: class ClassDump
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\ClassDump.java:36: error: cannot find symbol
        public void setClassFilter(ClassFilter cf) {
                                   ^
  symbol:   class ClassFilter
  location: class ClassDump
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\ClassDump.java:121: error: cannot find symbol
        private void dumpKlass(InstanceKlass kls) {
                               ^
  symbol:   class InstanceKlass
  location: class ClassDump
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\EntryPoint.java:3: error: package com.sun.tools.attach does not exist
import com.sun.tools.attach.VirtualMachine;
                           ^
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\EntryPoint.java:4: error: package com.sun.tools.attach does not exist
import com.sun.tools.attach.VirtualMachineDescriptor;
                           ^
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\EntryPoint.java:15: error: cannot find symbol
        private static List<VirtualMachineDescriptor> vms;
                            ^
  symbol:   class VirtualMachineDescriptor
  location: class EntryPoint
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\EntryPoint.java:58: error: cannot find symbol
        private static VirtualMachineDescriptor getVm(int pid) {
                       ^
  symbol:   class VirtualMachineDescriptor
  location: class EntryPoint
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\tools\ClassListTool.java:3: error: package sun.jvm.hotspot.tools does not exist
import sun.jvm.hotspot.tools.Tool;
                            ^
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\tools\ClassListTool.java:8: error: cannot find symbol
public class ClassListTool extends Tool {
                                   ^
  symbol: class Tool
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\tools\DumperTool.java:5: error: package sun.jvm.hotspot.tools does not exist
import sun.jvm.hotspot.tools.Tool;
                            ^
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\tools\DumperTool.java:14: error: cannot find symbol
public class DumperTool extends Tool {
                                ^
  symbol: class Tool
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\tools\EntryDumper.java:3: warning: Agent is internal proprietary API and may be removed in a future release
import sun.management.Agent;
                     ^
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\Utils.java:3: error: package com.sun.tools.attach does not exist
import com.sun.tools.attach.VirtualMachineDescriptor;
                           ^
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\Utils.java:4: error: package sun.jvm.hotspot.tools does not exist
import sun.jvm.hotspot.tools.Tool;
                            ^
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\Utils.java:12: error: cannot find symbol
        static void executeJavaAgent(Tool agent, VirtualMachineDescriptor vm) {
                                     ^
  symbol:   class Tool
  location: class Utils
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\Utils.java:12: error: cannot find symbol
        static void executeJavaAgent(Tool agent, VirtualMachineDescriptor vm) {
                                                 ^
  symbol:   class VirtualMachineDescriptor
  location: class Utils
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\ClassDump.java:68: error: cannot find symbol
                                                this.classFilter = (ClassFilter) filterClass.newInstance();
                                                                    ^
  symbol:   class ClassFilter
  location: class ClassDump
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\ClassDump.java:72: error: cannot find symbol
                                                this.classFilter = (ClassFilter) con.newInstance(this.pkgList);
                                                                    ^
  symbol:   class ClassFilter
  location: class ClassDump
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\ClassDump.java:85: error: cannot find symbol
                        SystemDictionary dict = VM.getVM().getSystemDictionary();
                        ^
  symbol:   class SystemDictionary
  location: class ClassDump
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\ClassDump.java:85: error: cannot find symbol
                        SystemDictionary dict = VM.getVM().getSystemDictionary();
                                                ^
  symbol:   variable VM
  location: class ClassDump
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\ClassDump.java:88: error: cannot find symbol
                                if (k instanceof InstanceKlass) {
                                                 ^
  symbol:   class InstanceKlass
  location: class ClassDump
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\ClassDump.java:90: error: cannot find symbol
                                                dumpKlass((InstanceKlass) k);
                                                           ^
  symbol:   class InstanceKlass
  location: class ClassDump
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\ClassDump.java:99: error: cannot find symbol
                catch (AddressException var6) {
                       ^
  symbol:   class AddressException
  location: class ClassDump
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\ClassDump.java:149: error: cannot find symbol
                                        ClassWriter cw = new ClassWriter(kls, os);
                                        ^
  symbol:   class ClassWriter
  location: class ClassDump
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\ClassDump.java:149: error: cannot find symbol
                                        ClassWriter cw = new ClassWriter(kls, os);
                                                             ^
  symbol:   class ClassWriter
  location: class ClassDump
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\EntryPoint.java:23: error: cannot find symbol
                vms = VirtualMachine.list();
                      ^
  symbol:   variable VirtualMachine
  location: class EntryPoint
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\EntryPoint.java:28: error: cannot find symbol
                                        .map(VirtualMachineDescriptor::toString)
                                             ^
  symbol:   variable VirtualMachineDescriptor
  location: class EntryPoint
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\EntryPoint.java:35: error: cannot find symbol
                                VirtualMachineDescriptor vm = getVm(id);
                                ^
  symbol:   class VirtualMachineDescriptor
  location: class EntryPoint
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\EntryPoint.java:48: error: cannot find symbol
                        VirtualMachineDescriptor vm = getVm(id);
                        ^
  symbol:   class VirtualMachineDescriptor
  location: class EntryPoint
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\EntryPoint.java:59: error: cannot find symbol
                VirtualMachineDescriptor vm =
                ^
  symbol:   class VirtualMachineDescriptor
  location: class EntryPoint
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\tools\ClassListTool.java:43: error: method does not override or implement a method from a supertype
        @Override
        ^
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\tools\ClassListTool.java:46: error: package sun.jvm.hotspot.runtime does not exist
                sun.jvm.hotspot.runtime.VM.getVM().getSystemDictionary().classesDo(klass ->
                                       ^
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\tools\DumperTool.java:15: error: method does not override or implement a method from a supertype
        @Override
        ^
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\tools\EntryDumper.java:16: warning: Agent is internal proprietary API and may be removed in a future release
public class EntryDumper extends Agent {
                                 ^
C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\Utils.java:14: error: cannot find symbol
                        Method m = Tool.class.getDeclaredMethod("start", String[].class);
                                   ^
  symbol:   class Tool
  location: class Utils
Note: C:\Users\omegabr\Desktop\JvmClassDumper-master\JvmClassDumper-master\src\main\java\cookiedragon\dumper\ClassDump.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Comment by RealXor** [comment]
Tools.jar is not in the current classpath, make sure to load it.
